"""Build Scratch SD bridge slides using the project's established bridge design system."""
from pathlib import Path
import html, json

ROOT = Path(__file__).resolve().parents[1]
SLIDES = ROOT / "slides"
DRAFT = ROOT / "drafts" / "sd-scratch"
REFERENCE = SLIDES / "bridge-ms-00.html"
SLIDES.mkdir(exist_ok=True); DRAFT.mkdir(parents=True, exist_ok=True)

raw = REFERENCE.read_text(encoding="utf-8")
css = raw.split("<style>", 1)[1].split("</style>", 1)[0]
css += """
.source{font-size:14px;color:#333;margin-top:18px}.source a{color:#0056b3}.image-note{font-size:15px;font-weight:600;margin-top:8px;color:#333}.screenshot-box img{max-height:330px}.feature-card p,.feature-card li{font-size:18px;line-height:1.5}.mini-card{background:#fff;border:3px solid var(--black);border-radius:14px;padding:16px;box-shadow:4px 4px 0 var(--black);margin-bottom:12px}.mini-card h3{margin:0 0 8px}.two-column{align-items:stretch}.slide-text img{max-width:100%}
"""

IMG = "../assets/scratch/"
def image(file, alt, caption):
    return f'''<div class="screenshot-box"><img src="{IMG}{file}" alt="{html.escape(alt)}" class="screenshot-img"><div class="screenshot-caption">🖼️ {html.escape(caption)}</div></div>'''
def card(title, body, style=""):
    return f'<div class="mini-card" style="{style}"><h3>{title}</h3><p>{body}</p></div>'
def slide(title, subtitle, body):
    return f'''<div class="slide" data-title="{html.escape(title)}" data-subtitle="{html.escape(subtitle)}"><div class="content-card"><div class="inner-content"><h2 class="slide-title">{title}</h2><div class="slide-text">{body}</div></div></div></div>'''
def quiz(question, options, answer):
    opts = "".join(f'<button class="quiz-option" onclick="this.parentElement.querySelectorAll(\'.quiz-option\').forEach(x=>x.classList.remove(\'correct\',\'wrong\'));this.classList.add(\'{"correct" if i==answer else "wrong"}\')">{chr(65+i)}. {x}</button>' for i,x in enumerate(options))
    return f'<div class="feature-card quiz"><h3>🧠 Cek pemahaman</h3><p>{question}</p>{opts}</div>'

def nav(n):
    return f'''<div class="nav-container"><button id="btnPrev" class="nav-btn" disabled>← Prev</button><div class="counter-group"><div class="slide-counter">Slide <span id="counter">1</span> dari <span id="totalSlides">{n}</span></div><div class="progress-bar-bg"><div id="bar" class="progress-bar" style="width:6.25%"></div></div></div><button id="btnNext" class="nav-btn">Next →</button></div>'''

def html_doc(meta, sections):
    slides = ''.join(slide(*x) for x in sections)
    return f'''<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>{html.escape(meta['title'])}</title><style>{css}</style></head><body><div class="app-container"><div class="header"><div class="banner-container"><div class="banner-shape"><div id="banner-title" class="banner-text">{html.escape(sections[0][0])}</div></div><div id="banner-subtitle" class="banner-subtitle">{html.escape(sections[0][1])}</div></div></div><div class="slides-area">{slides}</div>{nav(len(sections))}</div><script>const slides=document.querySelectorAll('.slide'),bar=document.getElementById('bar'),counter=document.getElementById('counter'),btnPrev=document.getElementById('btnPrev'),btnNext=document.getElementById('btnNext');let currentSlide=0;function showSlide(index){{if(index<0)index=0;if(index>=slides.length)index=slides.length-1;slides.forEach(s=>s.classList.remove('active'));currentSlide=index;slides[currentSlide].classList.add('active');const c=slides[currentSlide].querySelector('.content-card');if(c)c.scrollTo(0,0);btnPrev.disabled=currentSlide===0;btnNext.disabled=currentSlide===slides.length-1;counter.innerText=currentSlide+1;bar.style.width=((currentSlide+1)/slides.length*100)+'%';document.getElementById('banner-title').innerText=slides[currentSlide].dataset.title;document.getElementById('banner-subtitle').innerText=slides[currentSlide].dataset.subtitle}}btnNext.onclick=()=>showSlide(currentSlide+1);btnPrev.onclick=()=>showSlide(currentSlide-1);document.addEventListener('keydown',e=>{{if(e.key==='ArrowRight'||e.key===' ')showSlide(currentSlide+1);if(e.key==='ArrowLeft')showSlide(currentSlide-1)}});showSlide(0);</script></body></html>'''

common_source = '<p class="source">Visual berasal dari artikel <a href="https://www.create-learn.us/blog/how-do-i-learn-scratch-coding-with-scratch-for-kids-explained/">Create & Learn — How to Use Scratch</a>. Digunakan sebagai referensi belajar, bukan ilustrasi buatan ulang.</p>'

content = {
'bridge-sd-00': ({'kicker':'Materi Jembatan 00 · Kenalan Scratch','title':'Scratch dari Nol: Kenalan dengan Platformnya','summary':'Orientasi platform Scratch menggunakan referensi visual aktual dari Create & Learn.','objectives':['Menjelaskan Scratch sebagai platform coding berbasis blok','Mengenali Stage, Sprite, Block Palette, dan Coding Area','Membuat dan menjalankan project pertama','Mengetahui troubleshooting dasar']}, [
('Selamat Datang di Scratch','Scratch · Platform Coding Visual','<div class="content-card" style="align-items:center;justify-content:center;background:radial-gradient(circle,var(--blue) 0%,#0056b3 100%);color:var(--white)"><div class="inner-content" style="text-align:center"><span style="background-color:var(--yellow);color:var(--black);padding:8px 24px;border:3px solid var(--black);border-radius:20px;font-size:18px;font-weight:700;box-shadow:4px 4px 0 var(--black);display:inline-block">UOB MY DIGITAL SPACE • SD 🎨</span><h1 style="font-size:46px;text-shadow:4px 4px 0 var(--black)">Yuk, Kenalan dengan Scratch!</h1><p style="font-size:23px;color:var(--yellow)">Tempat membuat cerita, animasi, dan game dengan balok kode</p>'+image('cl-scratch-editor.png','Tampilan Scratch dari artikel Create & Learn','Contoh tampilan editor Scratch')+'</div></div>'),
('Scratch itu apa?','Platform Coding Visual','<p>Scratch adalah platform gratis berbasis blok untuk membuat <b>cerita, animasi, dan game</b>. Kita menyusun balok seperti puzzle, jadi bisa fokus pada logika tanpa sibuk mengetik sintaks.</p>'+image('cl-scratch-overview.png','Contoh project Scratch dari artikel Create & Learn','Contoh karya yang dapat dibuat di Scratch')+common_source),
('Kenali ruang kerjanya','Block Palette · Coding Area · Stage · Sprite','<div class="two-column"><div>'+card('Block Palette','Tempat mengambil blok kode berwarna.')+card('Coding Area','Tempat menyambungkan balok.')+'</div><div>'+card('Stage','Tempat project berjalan.')+card('Sprite & Backdrop','Tempat mengatur karakter dan latar.')+'</div></div>'+image('cl-scratch-editor.png','Antarmuka editor Scratch','Gunakan gambar aktual sebagai peta ruang kerja')), 
('Warna dan bentuk blok','Blok kode Scratch','<div class="two-column">'+image('cl-event-blocks.png','Blok Events Scratch','Events adalah pemicu script')+image('cl-motion-blocks.png','Blok Motion Scratch','Motion mengatur gerak Sprite')+'</div><p>Setiap kategori memiliki warna dan bentuk sendiri. Blok Events biasanya menjadi awal script. Pilih blok asli dari palette Scratch lalu sambungkan di Coding Area.</p>'),
('Coba project pertamamu','Green Flag · Say','<p>Ikuti langkah ini langsung di Scratch:</p><ol><li>Pilih satu Sprite.</li><li>Ambil blok Events dari palette.</li><li>Ambil blok Looks untuk membuat Sprite berbicara.</li><li>Sambungkan, lalu klik bendera hijau.</li></ol>'+image('cl-looks-blocks.png','Blok Looks Scratch','Pilih blok Looks langsung dari Scratch')+quiz('Apa yang biasanya menjadi awal script?', ['Blok Motion','Blok Events','Blok Sound','Blok Variables'],1)),
('Kalau belum berjalan...','Troubleshooting Dasar','<div class="two-column"><div>'+card('Script tidak mulai','Pastikan ada blok Events di paling atas.')+card('Sprite terbalik','Atur Rotation Style menjadi Left-Right.')+'</div><div>'+card('Animasi hanya sekali','Gunakan Repeat atau Forever.')+card('Sensing tidak bereaksi','Cek berulang di dalam Forever.')+'</div></div>'+common_source)
]),
'bridge-sd-01': ({'kicker':'Materi Jembatan 01 · Project About Me','title':'Dari Karakter ke Kode: Sprite, Costume, dan Event','summary':'Jembatan sebelum playlist About Me dengan visual Scratch aktual.','objectives':['Membedakan Sprite, Costume, dan Backdrop','Menggunakan event green flag dan sprite click','Menggabungkan Looks dan Sound untuk perkenalan']}, [
('Siapkan Project About Me','Project 1 · Perkenalan Interaktif','<p>Project pertama kita adalah kartu perkenalan interaktif. Karakter, suara, makanan favorit, dan hobimu boleh berbeda dengan contoh.</p>'+image('cl-scratch-editor.png','Editor Scratch','Mulai dari Sprite yang kamu pilih sendiri')),
('Sprite, Costume, Backdrop','Objek · Tampilan · Latar','<div class="two-column"><div>'+card('Sprite','Karakter atau benda yang diberi kode.')+card('Costume','Tampilan berbeda dari satu Sprite.')+'</div><div>'+card('Backdrop','Latar belakang Stage.')+card('Catatan','Satu Sprite dapat memiliki banyak Costume.')+'</div></div>'+image('cl-looks-blocks.png','Blok Looks Scratch','Looks mengatur tampilan dan Costume')),
('Event membuat project bereaksi','Green Flag · Sprite Click','<p>Gunakan Events sebagai pemicu. Untuk melihat blok aslinya, ambil dari palette Scratch—bukan menyalin bentuk dari teks.</p>'+image('cl-event-blocks.png','Blok Events Scratch','Contoh blok Events aktual')+quiz('Event apa yang cocok untuk aksi saat karakter diklik?', ['When green flag clicked','When this sprite clicked','When backdrop switches','When key pressed'],1)),
('Tambahkan suara dan cerita','Sound · Say · Record','<div class="two-column"><div>'+card('Say','Menampilkan perkenalan sebagai teks.')+card('Record','Merekam suara sendiri jika mau.')+'</div><div>'+card('Play sound','Memutar suara saat event terjadi.')+card('Uji','Cek volume dan durasi.')+'</div></div>'),
('Tantangan About Me','Design · Media · First Code','<ul><li>Wajib: satu Sprite dan satu perkenalan.</li><li>Pilih: tambahkan suara atau Emoji Sprite.</li><li>Kreatif: buat Costume makanan atau hobi.</li></ul>'+common_source)
]),
'bridge-sd-02': ({'kicker':'Materi Jembatan 02 · Loop dan Animasi','title':'Membuat Gerakan Berulang dengan Loop','summary':'Jembatan loop untuk About Me dan Racing Car menggunakan blok Scratch aktual.','objectives':['Membedakan aksi satu kali dan berulang','Memahami Repeat, Forever, dan Repeat Until','Menggunakan Move, Turn, Next Costume, dan Wait']}, [
('Mengapa butuh loop?','Control · Mengulang Aksi','<p>Loop memberi tahu Scratch untuk mengulang aksi tanpa menulis blok yang sama berkali-kali.</p>'+image('cl-control-blocks.png','Blok Control Scratch','Blok Control aktual dari sumber web')),
('Repeat, Forever, Repeat Until','Tiga jenis pengulangan','<div class="two-column"><div>'+card('Repeat','Mengulang sejumlah kali lalu berhenti.')+card('Forever','Mengulang terus selama project berjalan.')+'</div><div>'+card('Repeat Until','Mengulang sampai kondisi terpenuhi.')+card('Tips','Uji satu loop kecil sebelum menambah aksi.')+'</div></div>'+image('cl-control-blocks.png','Kategori Control Scratch','Ambil loop dari kategori Control')),
('Gerak adalah aksi kecil','Move · Turn · Wait','<p>Gabungkan blok Motion dengan Control. Ubah angka sedikit demi sedikit dan amati apa yang berubah.</p>'+image('cl-motion-blocks.png','Blok Motion Scratch','Blok Motion aktual dari sumber web')),
('Costume sebagai frame','Next Costume · Animation','<p>Animasi dapat dibuat dengan menampilkan Costume secara bergantian. Tambahkan jeda supaya perubahan terlihat.</p>'+image('cl-looks-blocks.png','Blok Looks Scratch','Blok Looks aktual untuk Costume')),
('Tantangan animasi','Lihat · Ubah · Uji','<div class="two-column"><div>'+card('Level 1','Gerakkan Sprite berulang.')+card('Level 2','Ganti Costume dengan jeda.')+'</div><div>'+card('Level 3','Tambahkan suara atau extension.')+'</div></div>'+quiz('Blok mana yang mengulang aksi?', ['Repeat','Move','Next Costume','Say'],0))
]),
'bridge-sd-03': ({'kicker':'Materi Jembatan 03 · Logika Game','title':'Input, Sensing, dan Keputusan di Racing Car','summary':'Jembatan sebelum coding Racing Car dengan blok Scratch aktual.','objectives':['Memahami input keyboard','Memahami loop pengecekan','Menggunakan Sensing dan If Then untuk aturan game']}, [
('Game membutuhkan input','Keyboard · Click · Touch','<p>Game menjadi interaktif karena program merespons tombol panah, klik, atau sentuhan objek.</p>'+image('cl-event-blocks.png','Blok Events Scratch','Events memulai respons terhadap input')),
('Gerak dan pengulangan','Repeat Until','<p>Untuk membuat mobil terus bergerak selama tombol ditekan, gunakan event keyboard dan loop. Ambil blok langsung dari palette Scratch.</p>'+image('cl-control-blocks.png','Blok Control Scratch','Control mengatur pengulangan gerak')),
('Sensing bertanya kepada game','Touching · Key Pressed','<p>Sensing memeriksa apa yang sedang terjadi di Stage: apakah menyentuh finish, mobil lain, atau tombol tertentu.</p>'+image('cl-sensing-blocks.png','Blok Sensing Scratch','Sensing mendeteksi interaksi')),
('If membuat aturan','Condition · Feedback','<p>Logikanya: <b>jika</b> menyentuh garis finish, <b>maka</b> tampilkan menang. Pengecekan yang terus berjalan ditempatkan di dalam loop.</p>'+image('cl-sensing-blocks.png','Blok Sensing Scratch','Gunakan Sensing sebagai kondisi')+quiz('Mengapa collision perlu dicek berulang?', ['Agar dicek terus-menerus','Agar Sprite hilang','Agar warna berubah','Agar project tersimpan'],0)),
('Racing Car: urutan kerja','Assets → Input → Logic','<ol><li>Desain sirkuit dan mobil.</li><li>Program input keyboard dan gerak.</li><li>Duplikasi mobil kedua.</li><li>Tambahkan finish line.</li><li>Tambahkan collision dan feedback menang.</li></ol>')
]),
'bridge-sd-04': ({'kicker':'Materi Jembatan 04 · Data dan Koordinasi','title':'Variable, Broadcast, dan Project Integratif','summary':'Jembatan sebelum Increase Your Earnings dengan visual blok Scratch aktual.','objectives':['Menjelaskan variable sebagai penyimpan nilai','Membuat counter Score atau Credit','Menjelaskan Broadcast sebagai pesan antar-Sprite','Menghubungkan backdrop, kondisi, dan ending']}, [
('Variable adalah kotak nilai','Score · Credit · Lives','<p>Variable menyimpan nilai yang dapat berubah. Contohnya Score, Credit, atau Lives.</p>'+image('cl-variable-blocks.png','Blok Variables Scratch','Kategori Variables aktual dari sumber web')),
('Atur nilai awal','Set · Change','<div class="two-column"><div>'+card('Awal project','Atur Score atau Credit ke 0.')+card('Aksi berhasil','Naikkan nilai setelah tugas selesai.')+'</div><div>'+card('Aturan','Periksa apakah Credit sudah cukup.')+'</div></div>'+image('cl-variable-blocks.png','Blok Variables Scratch','Ambil Set dan Change dari palette')),
('Broadcast adalah pesan','Kirim · Terima · Respons','<p>Broadcast membantu Sprite bekerja sama. Satu Sprite mengirim pesan, Sprite lain menerima lalu merespons.</p>'+image('cl-event-blocks.png','Blok Events Scratch','Events menjadi tempat pesan dipicu')),
('Backdrop adalah babak cerita','Scene · State','<ol><li>Living room: percakapan pembuka.</li><li>Lokasi tugas: pemain beraktivitas.</li><li>Living room lagi: Credit diperbarui.</li><li>Ending: kondisi tujuan tercapai.</li></ol><div class="quote-box">State artinya project sedang berada di babak yang mana.</div>'),
('Increase Your Earnings','Capstone Project 3','<div class="two-column"><div>'+card('Video 1','Pahami brief dan remix starter project.')+card('Video 2','Buat pilihan pertama dan scene.')+'</div><div>'+card('Video 3','Tambahkan pilihan kedua dan Credit.')+card('Video 4','Buat ending kondisional.')+'</div></div>'),
('Checklist sebelum capstone','Siap Membuat Project','<ul><li>Aku tahu Sprite mana yang dipilih.</li><li>Aku paham Event dan Loop.</li><li>Aku bisa membuat variable.</li><li>Aku tahu Broadcast adalah pesan antar-Sprite.</li><li>Aku siap menguji satu fitur kecil dulu.</li></ul>'+quiz('Apa fungsi utama variable Credit?', ['Mengubah warna Stage','Menyimpan nilai Credit yang berubah','Memilih Sprite','Mengulang suara'],1)),
('Peta Scratch Async SD','Bridge → Project → Capstone','<div class="two-column"><div>'+card('Bridge 00','Kenalan platform.')+card('About Me','Media, Event, Costume, Animasi.')+card('Bridge 02','Loop.')+'</div><div>'+card('Racing Car','Input, Sensing, Conditional.')+card('Bridge 04','Variable dan Broadcast.')+card('Increase Your Earnings','Capstone.')+'</div></div>'+common_source)
])}

for key,(meta,sections) in content.items():
    meta=dict(meta,id=key,type='slide',level='SD',totalSlides=len(sections),slideUrl=f'./slides/{key}.html',embedUrl=f'slides/{key}.html',prerequisiteStepIds=[])
    meta['learningObjectives']=meta.pop('objectives')
    meta['practice']={'type':'guided_reading','description':'Menyelesaikan pembacaan, observasi visual, dan checkpoint quiz.'}
    meta['completionCriteria']={'quizScoreMin':100,'interactiveCompleted':True,'description':'Menyelesaikan semua slide dan checkpoint quiz.'}
    meta['bookmarks']=[{'slideIndex':i,'label':x[0]} for i,x in enumerate(sections)]
    meta['quizzes']=[{'question':'Checkpoint tersedia di dalam slide interaktif.','options':['Baca ulang slide','Lanjut tanpa mencoba','Tutup materi'],'answer':0,'explanation':'Baca ulang bagian yang belum jelas lalu coba lagi.','embedded':True}]
    (SLIDES/f'{key}.html').write_text(html_doc(meta,sections),encoding='utf-8')
    (SLIDES/f'{key}.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2),encoding='utf-8')
    (DRAFT/f'{key}.json').write_text(json.dumps(meta,ensure_ascii=False,indent=2),encoding='utf-8')
print('Rebuilt',len(content),'Scratch SD bridges with existing bridge design and real Scratch visuals.')
